export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jfif",
    username: "AviPinto",
  },
  {
    id: 2,
    profilePicture: "person/2.jfif",
    username: "David Pinto",
  },
  {
    id: 3,
    profilePicture: "person/3.jfif",
    username: "Liza Pinto",
  },
  {
    id: 4,
    profilePicture: "person/4.jfif",
    username: "Haim Pinto",
  },
  {
    id: 5,
    profilePicture: "person/5.jfif",
    username: "Moshe Cohen",
  },
  {
    id: 6,
    profilePicture: "person/6.jfif",
    username: "Michael Jordan",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "Daniel Alves",
  },
  {
    id: 8,
    profilePicture: "person/8.jfif",
    username: "Cristiano Ronaldo",
  },
  {
    id: 9,
    profilePicture: "person/9.jfif",
    username: "Dror levi",
  },
  {
    id: 10,
    profilePicture: "person/10.jpg",
    username: "Ben Cohen",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Lov,e For All",
    photo: "post/1.jfif",
    date: "5 min ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "good day",
    photo: "post/2.jfif",
    date: "15 min ago",
    userId: 2,
    like: 2,
    comment: 13,
  },
  {
    id: 3,
    desc: "bla bla",
    photo: "post/3.jfif",
    date: "20 min ago",
    userId: 3,
    like: 35,
    comment: 7,
  },
  {
    id: 4,
    desc: "Hello new york",
    photo: "post/4.jpg",
    date: "25 min ago",
    userId: 4,
    like: 11,
    comment: 11,
  },
  {
    id: 5,
    desc: "woowww!",
    photo: "post/5.webp",
    date: "26 min ago",
    userId: 5,
    like: 4,
    comment: 9,
  },
  {
    id: 6,
    desc: "bla bla",
    photo: "post/6.jfif",
    date: "30 min ago",
    userId: 6,
    like: 2,
    comment: 5,
  },
  {
    id: 7,
    desc: "booom!",
    photo: "post/7.jpg",
    date: "31 min ago",
    userId: 7,
    like: 3,
    comment: 7,
  },
  {
    id: 8,
    desc: "Lov,e For All",
    photo: "post/8.jfif",
    date: "40 min ago",
    userId: 8,
    like: 35,
    comment: 8,
  },
  {
    id: 9,
    desc: "good morning",
    photo: "post/9.jpg",
    date: "45 min ago",
    userId: 9,
    like: 43,
    comment: 5,
  },
  {
    id: 10,
    desc: "good evening friends",
    photo: "post/10.jpg",
    date: "59 min ago",
    userId: 10,
    like: 403,
    comment: 105,
  },
];
